#!/bin/sh

if [[ -z "$1" ]] || [[ "$1" = '1' ]] || [[ "$1" = 'dwm' ]]; then
	pgrep dwm || startx $HOME/.config/x11-a/xinitrc

elif [[ "$1" = '2' ]] || [[ "$1" = 'exwm' ]]; then
	pgrep i3 || startx $HOME/.config/x11-b/xinitrc

elif [[ "$1" = '3' ]] || [[ "$1" = 'gnome' ]]; then
	#pgrep gnome-session || MOZ_ENABLE_WAYLAND=1 QT_QPA_PLATFORM=wayland XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session
  pgrep gnome-session || startx $HOME/.config/x11-c/xinitrc
fi
