#!/bin/bash
cd "$1" || exit
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit

branch=$(git branch --show-current)

if [ -n "$(git status --porcelain)" ]; then
  printf " %s* " "$branch"
else
  printf " %s " "$branch"
fi
