#!/bin/sh

# Rescan for available Wi-Fi networks
$(nmcli dev wifi rescan)

if [ "$XDG_SESSION_TYPE" = wayland ]; then
  wifiBSSID=$(nmcli -f BSSID,SSID,SIGNAL,BARS dev wifi list | sed -n '1!p' | tofi -c ~/.config/tofi/configW --prompt-text "Select wifi:" | cut -d' ' -f1)
  
  if [ -n "$wifiBSSID" ]; then
      # Try connecting to the selected Wi-Fi network
      if ! conStat=$(nmcli dev wifi connect "$wifiSSID" 2>&1); then
          # If connection fails, prompt for password
          wifiPass=$(echo "" | tofi -c ~/.config/tofi/configW --prompt-text "Enter password: " --require-match=false)
          conStat=$(nmcli dev wifi connect "$wifiSSID" password "$wifiPass")
      fi
    else
      echo "" | timeout 1 tofi -c ~/.config/tofi/configW --prompt-text "Aborted\!"
  fi

else
  # Get the selected Wi-Fi SSID using dmenu
  wifiBSSID=$(nmcli -f BSSID,SSID,SIGNAL,BARS dev wifi list | sed -n '1!p' | dmenu -i -p "Select wifi:" -l 20 | cut -d' ' -f1)
  if [ -n "$wifiBSSID" ]; then
      # Try connecting to the selected Wi-Fi network
      if ! conStat=$(nmcli dev wifi connect "$wifiSSID" 2>&1); then
          # If connection fails, prompt for password
          wifiPass=$(echo "" | dmenu -p "Enter password: ")
          conStat=$(nmcli dev wifi connect "$wifiSSID" password "$wifiPass")
      fi
  
      if [ -n "$conStat" ]; then
          # Display the connection status using dmenu
          echo "${conStat:5}" | timeout 1 dmenu -fn "JetBrainsMono:size=8"
          #timeout 1 dmenu -p "$conStat"
      fi
  else
      # Display a message if the user aborts the operation
      #echo "Aborted" | timeout 1 dmenu -fn "JetBrainsMono:size=10"
      timeout 1 dmenu -p "Aborted!"
  fi
fi 
